name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run lint
        uses: golangci/golangci-lint-action@v4
